# Jekyll configuration

name: Angle Net
description: Software Developer

# Url is currently only used only for the RSS feed in feed.xml
#url: https://anglenet.github.io
url: http://localhost:7777

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: '/'

social:
  github: AngleNet 
  #stackoverflow: ''
  #linkedin: ''
  #instagram: ''
  #lastfm: ''
  #rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blanc to ignore or put true to use
yandex_metrika:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: AngleNet 
comments: false 

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: pygments
markdown: kramdown 

kramdown:
    math_engine: mathjax

#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
